### ISSUE TITLE
环信的图片上传还是在后台做比较好

### ISSUE THREAD

**Issue by gelove** [zhaomenghuan/mui-demo#1]
现在这样在主页面和聊天页面都有连接这样比较奇怪吧。环信的连接和监听都在主页，然后通过自定义事件来发送短信，demo里没必要做图片发送，用input做发送体验很不好，选择照片那个弹出框很坑。发送消息、图片、语音、文件这些主要是通过后台来做，最好可以开发一个原生的组件出来，因为只有原生的才能视频聊天。只是一点小建议，你这样做的demo已经很好了

**Comment by zhaomenghuan** [comment]
谢谢你的意见，环信图片，语音这块demo最新版本将会更新，不过考虑到集成成本，js sdk能够解决的就不用原生，这个demo只是仅供参考，更好的体验自然是用原生sdk集成。
