### ISSUE TITLE
怎么有的demo在github，有的在rawgit.com，问题是rawgit.com打不开！！！

### ISSUE THREAD

**Issue by apkJava** [zhaomenghuan/mui-demo#11]
怎么有的demo在github，有的在rawgit.com，问题是rawgit.com打不开！！！
我想看时间轴的demo，打不开！打不开！打不开！

**Comment by zhaomenghuan** [comment]
rawgit.com 是 github 一个在线预览效果的网站，这个网站现在应该不能用了，内容没有更新了，这个仓库地址里面包含了代码。
