### ISSUE TITLE
“vue-mui：基于Vue.js的mui tabbar演示例子”中tab点击显示异常的问题

### ISSUE THREAD

**Issue by lishide** [zhaomenghuan/mui-demo#6]
点击已选定的tab，当前页面反复闪烁，不能正常显示。
本人在tab点击方法中添加了如下代码：
// 判断当前点击tab
if(targetTab == this.activeTab) {
	return;
}
是否可行？
新手，忘指点！

**Comment by zhaomenghuan** [comment]
可行，正确的做法应该是这样的，点击当前tab应该是不需要进行处理，直接return.

**Comment by lishide** [comment]
还有一个问题是多个tab里都有网络请求，它会同时发起请求，能不能切换到相应的tab再请求该页面所需的数据？

**Comment by zhaomenghuan** [comment]
@lishide 可以看看双首页配置方法，可以很好的解决你说的这个问题。https://segmentfault.com/a/1190000005340854#articleHeader18

**Comment by lishide** [comment]
可否分享出一个这种配置方案并且结合Vue实现首页的页面来，应该还有人有此需求，希望能优化一下index.html，谢谢！

**Comment by zhaomenghuan** [comment]
@lishide 可以看看我这里的一个例子：[https://github.com/vue-html5plus/vue-html5plus-template](https://github.com/vue-html5plus/vue-html5plus-template)，具体的可以我在这次讲座中有讲到：[html5+ App开发工程化实践之路](https://segmentfault.com/l/1500000009542402?r=bPqXdU)。欢迎参与一下，也算是对鄙人的一种支持吧。

**Comment by lishide** [comment]
看了template的例子，试着修改了我的，但是发现第一个tab会加入2次，底下是一个带顶部标题栏的页面，上面又出现一个不带标题的页面，按一次返回键后恢复正常。能帮忙看下问题出在哪了吗？

**Comment by lishide** [comment]
已修复，问题出在先在manifest配置了双首页，那种方案没解决，又使用了template例子中的方法，结果manifest的配置没删除。按照您的vue-mui和template例子，配置了兼容手机plus和浏览器环境（Iframe），感谢作者分享。
